spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop
    username: root
    password: ewq321!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# JWT secret key
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 스웨거 접근 UI 경로
    groups-order: DESC # 그룹 정렬 순서 설정
    operationsSorter: method # 작업(endpoint) 정렬 방법을 설정. method -> HTTP 메서드 순으로 정렬
    disable-swagger-default-url: true # 기본 Swagger URL 사용을 비활성화. 대신 /api 경로를 사용하여 Swagger에 액세스할 수 있음
    display-request-duration: true # 요청 지속 시간을 표시 여부
    defaultModelsExpandDepth: -1 # 기본 모델 확장 깊이를 설정. -1로 설정하면 모든 모델
#  api-docs:
#    path: /api # Swagger 문서의 경로를 설정. /api 경로를 사용하여 API 문서에 액세스.
#    show-actuator: true # Actuator 엔드포인트를 표시할지 여부를 설정.
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  paths-to-match:
#    - /**